<BoxLayout>:
    orientation: "vertical"
    spacing: 10
    padding: 10
    canvas.before:
        Rectangle:
            id: destination
            pos: self.pos
            size: self.size
    Button:
        text: "One One One"     
    Button:
        text: "two two two"
    Button:
        text: "three three three"
    Button:
        text: "four four four"
    Button:
        text: "five five five"		